import Link from 'next/link';
import { ArrowRight, CheckCircle2, ChevronRight, MonitorSmartphone, ShieldCheck, Sparkles } from 'lucide-react';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import FinalCTA from '../../components/FinalCTA';
import SEOHead from '../../components/SEOHead';
import { moduleMap } from '../../data/moduleCatalog';
import { roleMap, roles } from '../../data/roleCatalog';

export default function RoleDetail({role, linkedModules}){
  const schema={'@context':'https://schema.org','@type':'WebPage',name:`EduBridge ERP for ${role.title}`,description:role.summary,url:`https://www.edubridgeerp.in/roles/${role.slug}`};
  return <div className="bg-white text-slate-800"><SEOHead title={`${role.title} ERP Workspace | EduBridge`} description={`${role.summary} Explore role-specific capabilities, connected modules and mobile access in EduBridge ERP.`} path={`/roles/${role.slug}`} keywords={[`${role.title} ERP`,'education ERP','school ERP','college ERP']}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Navbar/><main>
    <section className="relative overflow-hidden bg-slate-950 py-16 text-white md:py-24"><div className="hero-grid absolute inset-0 opacity-25"/><div className="hero-glow hero-glow-one"/><div className="relative mx-auto max-w-7xl px-5 md:px-8"><div className="mb-8 flex flex-wrap items-center gap-2 text-xs font-semibold text-slate-400"><Link href="/">Home</Link><ChevronRight size={14}/><Link href="/roles">Roles</Link><ChevronRight size={14}/><span className="text-orange-400">{role.title}</span></div><div className="grid items-start gap-10 lg:grid-cols-[1.08fr_.92fr]"><div><span className="brand-kicker brand-kicker-dark">{role.eyebrow}</span><h1 className="mt-5 text-4xl font-black tracking-tight md:text-6xl">EduBridge for {role.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">{role.summary}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="btn-primary">Book a Role-Based Demo <ArrowRight size={18}/></Link><Link href="/modules" className="btn-secondary-dark">Explore Modules</Link></div></div><div className="glass-card-dark p-6 md:p-8"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-500"><Sparkles size={21}/></span><div><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">Role experience</p><h2 className="mt-1 text-xl font-black">Connected, focused, permission-aware</h2></div></div><div className="mt-6 grid gap-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><MonitorSmartphone className="text-orange-400" size={19}/><p className="mt-2 text-sm font-bold text-white">Web & mobile</p><p className="mt-1 text-sm leading-6 text-slate-400">{role.mobile}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><ShieldCheck className="text-orange-400" size={19}/><p className="mt-2 text-sm font-bold text-white">Role-aware access</p><p className="mt-1 text-sm leading-6 text-slate-400">Only relevant menus, actions and authorized institution data are exposed to the active role.</p></div></div></div></div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><span className="brand-kicker">Complete workspace</span><h2 className="mt-3 text-3xl font-black text-slate-950 md:text-4xl">What {role.title} can do</h2><p className="mt-4 leading-7 text-slate-600">This page groups the role-specific capabilities already connected across EduBridge modules.</p></div><div className="grid gap-3 sm:grid-cols-2">{role.features.map((feature,i)=><div key={feature} className="feature-row items-start"><span>{String(i+1).padStart(2,'0')}</span><p>{feature}</p></div>)}</div></div></div></section>
    <section className="bg-slate-50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid items-start gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="brand-kicker">Role outcomes</span><h2 className="mt-3 text-3xl font-black text-slate-950">Built around the day-to-day job.</h2></div><div className="grid gap-4 md:grid-cols-3">{role.outcomes.map(x=><div key={x} className="rounded-3xl border border-slate-200 bg-white p-6"><CheckCircle2 className="text-orange-500"/><h3 className="mt-5 font-bold leading-6 text-slate-950">{x}</h3></div>)}</div></div></div></section>
    {linkedModules.length>0 && <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-8"><span className="brand-kicker">Connected modules</span><h2 className="mt-3 text-3xl font-black text-slate-950">Key EduBridge modules for this role</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{linkedModules.map(m=><Link key={m.slug} href={`/modules/${m.slug}`} className="group rounded-3xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-xl"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{m.eyebrow}</p><h3 className="mt-3 text-xl font-black text-slate-950 group-hover:text-orange-600">{m.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{m.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-orange-600">View details <ArrowRight size={16}/></span></Link>)}</div></div></section>}
    <FinalCTA/>
  </main><Footer/></div>;
}

export async function getStaticPaths(){return {paths:roles.map(role=>({params:{slug:role.slug}})),fallback:false};}
export async function getStaticProps({params}){const role=roleMap[params.slug];const linkedModules=role.modules.map(slug=>moduleMap[slug]).filter(Boolean);return {props:{role,linkedModules}};}
