import Link from 'next/link';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import Navbar from './Navbar';
import Footer from './Footer';
import FinalCTA from './FinalCTA';
import SEOHead from './SEOHead';
import { moduleMap } from '../data/moduleCatalog';

export default function SolutionPage({ data, path }){
  const items=data.modules.map(slug=>moduleMap[slug]).filter(Boolean);
  return <div className="bg-white"><SEOHead title={`${data.title} | EduBridge ERP`} description={data.seo} path={path}/><Navbar/><main>
    <section className="relative overflow-hidden bg-slate-950 py-16 text-white md:py-24"><div className="hero-glow hero-glow-one"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 md:px-8 lg:grid-cols-2"><div><span className="brand-kicker brand-kicker-dark">{data.kicker}</span><h1 className="mt-5 text-4xl font-black tracking-tight md:text-6xl">{data.title}</h1><p className="mt-6 text-lg leading-8 text-slate-300">{data.description}</p><div className="mt-7 space-y-3">{data.bullets.map(x=><p key={x} className="flex gap-3 text-sm font-semibold text-slate-200"><CheckCircle2 size={19} className="shrink-0 text-orange-400"/>{x}</p>)}</div><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="btn-primary">Request a Demo <ArrowRight size={18}/></Link><Link href="/modules" className="btn-secondary-dark">Explore All Modules</Link></div></div><div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/5 p-2 shadow-2xl"><img src={data.image} alt={data.imageAlt} className="aspect-square w-full rounded-[1.6rem] object-cover"/></div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="max-w-3xl"><span className="brand-kicker">Connected capabilities</span><h2 className="mt-4 text-3xl font-black text-slate-950 md:text-5xl">Go deeper than a feature checklist.</h2><p className="mt-4 leading-7 text-slate-600">Each capability is connected to the wider EduBridge platform, reducing repeated data entry and fragmented workflows.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(item=><Link href={`/modules/${item.slug}`} key={item.slug} className="group rounded-3xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-xl"><span className="text-xs font-black uppercase tracking-wider text-orange-600">{item.eyebrow}</span><h3 className="mt-3 text-xl font-bold text-slate-950 group-hover:text-orange-600">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-orange-600">View module <ArrowRight size={15}/></span></Link>)}</div></div></section>
    <section className="bg-slate-50 py-16"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-6 md:grid-cols-3">{[['Connected by design','Modules share institution, student, staff and role context instead of living as isolated tools.'],['Mobile where it matters','Extend day-to-day workflows through role-based iOS and Android experiences.'],['Built to evolve','Use the modules you need now and expand the platform as your institution grows.']].map(([t,d])=><div key={t} className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="font-bold text-slate-950">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div></div></section><FinalCTA/>
  </main><Footer/></div>
}
