import Link from 'next/link';
import { Mail, MapPin, Phone, ArrowUpRight } from 'lucide-react';

const groups = [
  {title:'Platform',links:[['All Modules','/modules'],['Role Workspaces','/roles'],['School ERP','/school-erp'],['College ERP','/college-erp'],['AI-Powered ERP','/modules/ai-assistant'],['Branded Mobile Apps','/modules/branded-mobile-apps']]},
  {title:'Popular',links:[['Examination Role','/roles/examination'],['HOD Role','/roles/hod'],['Admissions CRM','/admission-crm'],['Exam Management','/exam-management'],['Library','/library'],['LMS & Assessments','/lms'],['Visitor Management','/visitor-management']]},
  {title:'Company',links:[['Features','/features'],['Contact','/contact'],['Privacy Policy','/privacy-policy'],['Terms & Conditions','/terms-and-conditions'],['Cancellation Policy','/cancellation-policy']]},
];
export default function Footer(){return <footer className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 pb-8 pt-16 md:px-8 md:pt-20"><div className="grid gap-12 lg:grid-cols-[1.2fr_1.8fr]"><div><img src="/logo.png" alt="EduBridge ERP" className="h-11 brightness-0 invert"/><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">AI-powered education ERP for schools, colleges and multi-campus institutions — connecting academics, exams, finance, HR, transport, operations, communication and branded mobile experiences.</p><div className="mt-6 space-y-3 text-sm text-slate-400"><a href="mailto:info@edubridgeerp.in" className="flex items-center gap-3 hover:text-white"><Mail size={17} className="text-orange-400"/>info@edubridgeerp.in</a><a href="tel:+919417873297" className="flex items-center gap-3 hover:text-white"><Phone size={17} className="text-orange-400"/>+91 94178 73297</a><div className="flex items-start gap-3"><MapPin size={17} className="mt-1 shrink-0 text-orange-400"/><span>NEXT57 Coworking, Plot F88, Industrial Area Phase 7, Sector 73, SAS Nagar, Mohali 160055</span></div></div></div><div className="grid gap-8 sm:grid-cols-3">{groups.map(g=><div key={g.title}><h3 className="text-sm font-bold uppercase tracking-[.16em] text-slate-300">{g.title}</h3><ul className="mt-5 space-y-3">{g.links.map(([label,href])=><li key={href}><Link href={href} className="group inline-flex items-center gap-1 text-sm text-slate-400 hover:text-white">{label}<ArrowUpRight size={12} className="opacity-0 transition group-hover:opacity-100"/></Link></li>)}</ul></div>)}</div></div><div className="mt-14 flex flex-col gap-3 border-t border-white/10 pt-7 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} EduBridge ERP. All rights reserved.</p><p>Education technology for modern institutions.</p></div></div></footer>}
