import Link from 'next/link';
import { ArrowRight, BrainCircuit, Building2, BusFront, CheckCircle2, ClipboardCheck, GraduationCap, Layers3, ShieldCheck, Smartphone, Sparkles, Users, WalletCards } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import FinalCTA from '../components/FinalCTA';
import ModuleCatalog from '../components/ModuleCatalog';
import RoleCatalog from '../components/RoleCatalog';
import SEOHead from '../components/SEOHead';

const pillars = [
  {icon:BrainCircuit,title:'AI-Powered Workflows',desc:'AI support for lesson planning, assessments, evaluation, academic improvement and management insight — with human review retained.'},
  {icon:Building2,title:'Schools + Colleges',desc:'One education ERP foundation for K-12 schools, colleges, campuses and multi-institution groups.'},
  {icon:Smartphone,title:'Branded iOS & Android Apps',desc:'Your institution name, logo and identity across connected role-based mobile experiences.'},
  {icon:ShieldCheck,title:'Role-Aware by Design',desc:'Management, Principal, HOD, Examination, teachers, students, accounts, HR, transport and other teams get focused workspaces.'},
];

const platformAreas = [
  ['Leadership & Principal','Command Center, AI, approvals, Student 360°, teacher performance and institution-wide monitoring','/roles/principal'],
  ['HOD & Departments','Academic monitoring, team, tasks, events, inventory, achievements and annual reports','/roles/hod'],
  ['Examination Department','Schemes, schedules, seating, invigilation, scripts, marks, results and report cards','/roles/examination'],
  ['Academics & Teachers','Attendance, timetable, syllabus, lesson plans, diary, assignments, LMS, PTM and online classes','/roles/teacher'],
  ['Fees & Accounts','Fee structures, collection, online payments, concessions, dues, receipts and finance reports','/roles/accounts'],
  ['HR & Staff','Employees, attendance, leave, payroll, documents, leadership and responsibilities','/roles/hr'],
  ['Transport & Driver','Routes, buses, live GPS, pickup/drop attendance, fees, staff and trip workflows','/roles/transport'],
  ['Campus Operations','Admissions, front office, visitors, gate passes, inventory, library, documents and safety','/modules'],
];

const roles=['Management','Principal','Admin','Academic Coordinator','HOD','Examination','Teacher','Student / Parent','Accounts','HR','Transport','Driver','Front Office','Admission','Inventory','Library','Health Staff'];

export default function Home(){
  const orgSchema={'@context':'https://schema.org','@type':'Organization',name:'EduBridge ERP',url:'https://www.edubridgeerp.in/',email:'info@edubridgeerp.in',telephone:'+91 94178 73297'};
  const softwareSchema={'@context':'https://schema.org','@type':'SoftwareApplication',name:'EduBridge ERP',applicationCategory:'EducationalApplication',operatingSystem:'Web, iOS, Android',description:'AI-powered education ERP for schools, colleges and multi-campus institutions with role-aware web and mobile experiences.'};
  return <div className="bg-white text-slate-800">
    <SEOHead title="EduBridge ERP | AI-Powered ERP for Schools & Colleges" description="AI-powered education ERP for schools and colleges with Principal Command Center, HOD, Examination, academics, fees, HR, transport, operations and institution-branded iOS & Android apps." path="/" keywords={['education ERP India','school ERP software','college ERP software','AI powered school ERP','examination management software','HOD department management ERP','principal dashboard ERP','branded school mobile app']} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(orgSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(softwareSchema)}}/>
    <Navbar/>
    <main>
      <section className="relative overflow-hidden bg-slate-950 text-white">
        <div className="hero-grid absolute inset-0 opacity-30"/><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/><div className="hero-ring hero-ring-one"/><div className="hero-ring hero-ring-two"/>
        <div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-14 px-5 py-16 md:px-8 lg:grid-cols-[1.02fr_.98fr] lg:py-24">
          <div className="relative z-10">
            <div className="inline-flex items-center gap-2 rounded-full border border-orange-400/25 bg-orange-400/10 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-orange-300"><Sparkles size={15}/> AI-Powered Education ERP</div>
            <h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.01] tracking-tight sm:text-5xl md:text-6xl lg:text-[4.65rem]">One intelligent ERP to run your <span className="gradient-text">entire institution.</span></h1>
            <p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 md:text-lg">From Principal Command Center and HOD departments to the complete Examination lifecycle, academics, admissions, fees, HR, transport and campus operations — EduBridge connects every team on web, iOS and Android.</p>
            <div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="btn-primary">Book a Live Demo <ArrowRight size={18}/></Link><Link href="/modules" className="btn-secondary-dark">Explore 100+ Workflows</Link></div>
            <div className="mt-9 grid max-w-2xl grid-cols-2 gap-3 text-sm text-slate-300 sm:grid-cols-4">{['Schools','Colleges','Multi-Campus','Web + Apps'].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 size={16} className="shrink-0 text-orange-400"/>{x}</span>)}</div>
            <div className="mt-8 flex flex-wrap gap-2">{['Principal Command Center','HOD Department OS','Examination Control','AI + Branded Apps'].map((x,i)=><span key={x} className={`hero-mini-pill ${i===2?'hero-mini-pill-accent':''}`}>{x}</span>)}</div>
          </div>

          <div className="relative mx-auto w-full max-w-[620px] lg:max-w-none">
            <div className="hero-console relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.06] p-3 shadow-2xl shadow-orange-500/10 backdrop-blur-xl md:p-4">
              <div className="mb-3 flex items-center justify-between rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-red-400/80"/><span className="h-2.5 w-2.5 rounded-full bg-amber-300/80"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-400/80"/></div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-slate-400"><Sparkles size={13} className="text-orange-400"/> EduBridge Control Center</div></div>
              <div className="relative overflow-hidden rounded-[1.4rem] bg-white"><img src="/images/screenshots/Admin.png" alt="EduBridge ERP administration dashboard" className="aspect-[4/3] w-full object-cover object-top"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/85 via-slate-950/25 to-transparent p-5 pt-16"><div className="grid grid-cols-3 gap-2"><div className="hero-stat"><b>17+</b><span>Role experiences</span></div><div className="hero-stat"><b>100+</b><span>Connected workflows</span></div><div className="hero-stat"><b>1</b><span>Institution data layer</span></div></div></div></div>
            </div>
            <div className="hero-float-card hero-float-exam"><span className="hero-float-icon"><ClipboardCheck size={19}/></span><div><b>Examination Department</b><small>Seating → Scripts → Results</small></div></div>
            <div className="hero-float-card hero-float-hod"><span className="hero-float-icon"><Building2 size={19}/></span><div><b>HOD Department OS</b><small>Academics + Tasks + Annual Report</small></div></div>
            <div className="hero-float-card hero-float-app"><span className="hero-float-icon"><Smartphone size={19}/></span><div><b>Your Branded Apps</b><small>iOS + Android</small></div></div>
            <div className="hero-ai-badge"><BrainCircuit size={16}/><span>AI inside real workflows</span></div>
          </div>
        </div>
      </section>

      <section className="border-b border-slate-100 bg-white py-7"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-7 gap-y-3 px-5 text-center text-[11px] font-black uppercase tracking-[.13em] text-slate-400 md:px-8">{roles.map(r=><span key={r}>{r}</span>)}</div></section>

      <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mx-auto max-w-3xl text-center"><span className="brand-kicker">Not just another school ERP</span><h2 className="mt-4 text-3xl font-black tracking-tight text-slate-950 md:text-5xl">An operating system for modern education.</h2><p className="mt-5 leading-7 text-slate-600">EduBridge is designed around how real schools and colleges work — leadership, departments, examinations, academics, finance, people, safety and communication all connected to the same institution data.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{pillars.map(({icon:Icon,title,desc})=><div key={title} className="premium-card"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-orange-600"><Icon size={23}/></span><h3 className="mt-5 text-lg font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p></div>)}</div></div></section>

      <section className="bg-slate-50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span className="brand-kicker">Role-first experience</span><h2 className="mt-3 max-w-4xl text-3xl font-black text-slate-950 md:text-5xl">Principal, HOD, Examination — and every team gets its own workspace.</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Decision-makers can now explore EduBridge by role and see the exact workflows each team receives.</p></div><Link href="/roles" className="inline-flex items-center gap-2 font-bold text-orange-600">Explore all role workspaces <ArrowRight size={18}/></Link></div><RoleCatalog compact/></div></section>

      <section className="overflow-hidden bg-slate-950 py-16 text-white md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-6 lg:grid-cols-2">
        <div className="relative overflow-hidden rounded-[2.25rem] border border-white/10 bg-white/[.06] p-7 md:p-9"><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-orange-500/10 blur-3xl"/><span className="brand-kicker brand-kicker-dark">Examination Department</span><h2 className="mt-5 text-3xl font-black md:text-4xl">From exam setup to checked answer scripts and final report cards.</h2><p className="mt-4 leading-7 text-slate-300">A complete connected examination workflow — not just marks entry.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Exam schemes & components','Date sheet & publication','Seating & invigilation','Exam attendance','Answer-script collection','Evaluator bundles & rechecks','Marks access & audit','Results & report cards'].map(x=><div key={x} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-3.5 text-sm font-semibold text-slate-200"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-orange-400"/>{x}</div>)}</div><Link href="/roles/examination" className="mt-8 inline-flex items-center gap-2 font-black text-orange-400">See complete Examination role <ArrowRight size={18}/></Link></div>
        <div className="relative overflow-hidden rounded-[2.25rem] border border-orange-400/20 bg-gradient-to-br from-orange-500/15 to-white/[.04] p-7 md:p-9"><span className="brand-kicker brand-kicker-dark">Department HOD</span><h2 className="mt-5 text-3xl font-black md:text-4xl">Turn every department into an accountable mini operating unit.</h2><p className="mt-4 leading-7 text-slate-300">HODs get academics + operations in one place, while Principal and Management retain visibility.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Teacher-wise academic monitoring','Lesson plans & syllabus progress','Diary activity','Department tasks','Events, duties & participants','Department inventory','Achievements & website publishing','One-Minute Annual Report'].map(x=><div key={x} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-3.5 text-sm font-semibold text-slate-200"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-orange-400"/>{x}</div>)}</div><Link href="/roles/hod" className="mt-8 inline-flex items-center gap-2 font-black text-orange-400">See complete HOD role <ArrowRight size={18}/></Link></div>
      </div></div></section>

      <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10"><span className="brand-kicker">Complete platform coverage</span><h2 className="mt-3 max-w-4xl text-3xl font-black text-slate-950 md:text-5xl">One ERP across the entire institution.</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{platformAreas.map(([title,desc,href],i)=><Link key={title} href={href} className={`group rounded-3xl border p-6 transition hover:-translate-y-1 hover:shadow-xl ${i===1||i===2?'border-orange-200 bg-orange-50/40':'border-slate-200 bg-white'}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-sm font-black text-white">{String(i+1).padStart(2,'0')}</span><h3 className="mt-5 text-xl font-black text-slate-950 group-hover:text-orange-600">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{desc}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-orange-600">Explore <ArrowRight size={15}/></span></Link>)}</div></div></section>

      <section className="bg-slate-50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="brand-kicker">Module by module</span><h2 className="mt-3 max-w-3xl text-3xl font-black text-slate-950 md:text-5xl">Every major workflow has a detailed page.</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Explore capabilities, role access, workflow, controls, reporting and connected modules — with dedicated deep dives for flagship areas.</p></div><Link href="/modules" className="inline-flex items-center gap-2 font-bold text-orange-600">View complete module catalog <ArrowRight size={18}/></Link></div><ModuleCatalog compact/></div></section>

      <section className="bg-white py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><div className="relative"><div className="absolute -inset-5 rounded-[3rem] bg-orange-100/70 blur-3xl"/><div className="relative grid grid-cols-2 gap-3"><img src="/images/screenshots/Student.png" alt="Student mobile experience" className="rounded-[2rem] border border-slate-200 shadow-xl"/><img src="/images/screenshots/Teacher.png" alt="Teacher mobile experience" className="mt-10 rounded-[2rem] border border-slate-200 shadow-xl"/></div></div><div><span className="brand-kicker">Your institution. Your apps.</span><h2 className="mt-4 text-3xl font-black text-slate-950 md:text-5xl">Institution-branded iOS & Android experiences.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Make the technology feel like part of your school or college — not a generic third-party portal. EduBridge can power connected mobile experiences under your institution’s name, logo and visual identity.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Student & Parent','Teacher','Accounts & HR','Transport & Driver','Examination','Academic Coordinator','Department HOD','Front Office'].map(x=><p key={x} className="flex gap-3 text-sm font-semibold text-slate-700"><CheckCircle2 size={19} className="shrink-0 text-orange-500"/>{x}</p>)}</div><Link href="/modules/branded-mobile-apps" className="mt-8 inline-flex items-center gap-2 font-bold text-orange-600">Explore branded mobile apps <ArrowRight size={18}/></Link></div></div></div></section>

      <section className="bg-orange-50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-5 lg:grid-cols-3"><div><span className="brand-kicker">Schools + Colleges</span><h2 className="mt-4 text-3xl font-black text-slate-950">Built to adapt to your institution.</h2><p className="mt-4 leading-7 text-slate-600">Preserve the strengths of your existing processes while moving departments onto one connected digital platform.</p></div><Link href="/school-erp" className="group rounded-[2rem] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Building2 size={28} className="text-orange-500"/><h3 className="mt-8 text-2xl font-black text-slate-950">For Schools</h3><p className="mt-3 leading-7 text-slate-600">K-12 academics, examinations, fees, transport, parent engagement, student wellbeing and campus operations.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-orange-600">School ERP <ArrowRight size={17}/></span></Link><Link href="/college-erp" className="group rounded-[2rem] bg-slate-950 p-7 text-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><GraduationCap size={28} className="text-orange-400"/><h3 className="mt-8 text-2xl font-black">For Colleges</h3><p className="mt-3 leading-7 text-slate-300">A flexible campus management foundation for academic administration, students, staff, finance, communication and operations.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-orange-400">College ERP <ArrowRight size={17}/></span></Link></div></div></section>
      <FinalCTA/>
    </main><Footer/>
  </div>
}
