import Link from 'next/link';
import { ArrowRight, BrainCircuit, Building2, CheckCircle2, GraduationCap, ShieldCheck, Smartphone, Sparkles, Users, BusFront, WalletCards, ClipboardCheck } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import FinalCTA from '../components/FinalCTA';
import ModuleCatalog from '../components/ModuleCatalog';
import SEOHead from '../components/SEOHead';

const pillars = [
  {icon:BrainCircuit,title:'AI-Powered Workflows',desc:'AI support for lesson planning, assessments, evaluation, academic improvement and management insights.'},
  {icon:Building2,title:'Built for Schools & Colleges',desc:'One education ERP architecture for K-12 schools, colleges and multi-campus institutions.'},
  {icon:Smartphone,title:'Branded iOS & Android Apps',desc:'Your institution name, logo and identity across role-based mobile experiences connected to the ERP.'},
  {icon:ShieldCheck,title:'Role-Aware by Design',desc:'Management, principal, teachers, students, accounts, HR, transport, HODs and other teams see the right workflows.'},
];
const audiences=[['Management & Principal','Command center, performance, approvals and institution-wide visibility',Users],['Academics & Examination','Timetable, syllabus, lesson plans, assessments, exams, scripts, marks and results',ClipboardCheck],['Accounts & Administration','Fees, online payments, concessions, reports, documents, visitors and gate operations',WalletCards],['Transport & Campus Teams','Routes, live bus tracking, transport attendance, inventory, library and operational workflows',BusFront]];
const roles=['Management','Principal','Admin','Coordinator','HOD','Teacher','Student / Parent','Accounts','HR','Examination','Transport','Driver','Front Office','Inventory','Library'];

export default function Home(){
  const orgSchema={'@context':'https://schema.org','@type':'Organization',name:'EduBridge ERP',url:'https://www.edubridgeerp.in/',email:'info@edubridgeerp.in',telephone:'+91 94178 73297'};
  const softwareSchema={'@context':'https://schema.org','@type':'SoftwareApplication',name:'EduBridge ERP',applicationCategory:'EducationalApplication',operatingSystem:'Web, iOS, Android',description:'AI-powered education ERP for schools, colleges and multi-campus institutions.'};
  return <div className="bg-white text-slate-800">
    <SEOHead title="EduBridge ERP | AI-Powered Education ERP for Schools & Colleges" description="AI-powered education ERP for schools, colleges and multi-campus institutions. Manage academics, exams, fees, HR, admissions, transport, operations and institution-branded iOS & Android apps." path="/" keywords={['education ERP India','school ERP software','college ERP software','AI powered school ERP','college management software','school management software','branded school mobile app']} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(orgSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(softwareSchema)}}/>
    <Navbar/>
    <main>
      <section className="relative overflow-hidden bg-slate-950 text-white">
        <div className="hero-grid absolute inset-0 opacity-30"/><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/>
        <div className="relative mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-5 py-16 md:px-8 lg:grid-cols-[1.03fr_.97fr] lg:py-24">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-orange-400/25 bg-orange-400/10 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-orange-300"><Sparkles size={15}/> AI-Powered Education ERP</div>
            <h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.02] tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">Run your entire institution from <span className="gradient-text">one intelligent platform.</span></h1>
            <p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 md:text-lg">EduBridge connects academics, examinations, admissions, finance, HR, transport, campus operations and communication — with role-based web access and institution-branded iOS & Android apps.</p>
            <div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="btn-primary">Request a Demo <ArrowRight size={18}/></Link><Link href="/modules" className="btn-secondary-dark">Explore All Modules</Link></div>
            <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-300">{['Schools','Colleges','Multi-Campus','Web + iOS + Android'].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 size={16} className="text-orange-400"/>{x}</span>)}</div>
          </div>
          <div className="relative lg:pl-5">
            <div className="absolute -left-6 top-12 hidden rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur-xl md:block"><p className="text-xs font-bold uppercase tracking-wider text-slate-300">Connected roles</p><p className="mt-1 text-2xl font-black">One ERP</p></div>
            <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/5 p-2 shadow-2xl shadow-orange-500/10 backdrop-blur"><img src="/images/screenshots/Admin.png" alt="EduBridge ERP administration dashboard" className="aspect-square w-full rounded-[1.6rem] object-cover"/></div>
            <div className="absolute -bottom-5 right-0 rounded-2xl border border-white/10 bg-slate-900/90 p-4 shadow-2xl backdrop-blur md:right-[-10px]"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-500"><Smartphone size={19}/></span><div><p className="text-sm font-bold">Institution-Branded Apps</p><p className="text-xs text-slate-400">iOS + Android</p></div></div></div>
          </div>
        </div>
      </section>

      <section className="border-b border-slate-100 bg-white py-7"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-8 gap-y-3 px-5 text-center text-xs font-bold uppercase tracking-[.14em] text-slate-400 md:px-8">{roles.map(r=><span key={r}>{r}</span>)}</div></section>

      <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mx-auto max-w-3xl text-center"><span className="brand-kicker">More than digitizing registers</span><h2 className="mt-4 text-3xl font-black tracking-tight text-slate-950 md:text-5xl">An operating system for modern education.</h2><p className="mt-5 leading-7 text-slate-600">Designed around how real institutions work — departments, approvals, academics, finance, people, safety and communication all connected to the same student and institution data.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{pillars.map(({icon:Icon,title,desc})=><div key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-50 text-orange-600"><Icon size={23}/></span><h3 className="mt-5 text-lg font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p></div>)}</div></div></section>

      <section className="bg-slate-50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="brand-kicker">Explore the platform</span><h2 className="mt-3 max-w-3xl text-3xl font-black text-slate-950 md:text-5xl">Every team gets the tools they actually need.</h2></div><Link href="/modules" className="inline-flex items-center gap-2 font-bold text-orange-600">View complete module catalog <ArrowRight size={18}/></Link></div><ModuleCatalog compact/></div></section>

      <section className="overflow-hidden bg-slate-950 py-16 text-white md:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 md:px-8 lg:grid-cols-2"><div><span className="brand-kicker brand-kicker-dark">For leadership</span><h2 className="mt-4 text-3xl font-black md:text-5xl">From “What is happening?” to “I can see it.”</h2><p className="mt-5 max-w-xl leading-7 text-slate-300">Management should not need ten calls and five spreadsheets to understand the day. EduBridge brings academic, operational and administrative signals into connected role-aware dashboards.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Institution Command Center','Unified Action Inbox','Teacher Performance & AI Insights','Student 360°'].map(x=><Link key={x} href={x==='Institution Command Center'?'/modules/institution-command-center':x==='Unified Action Inbox'?'/modules/action-inbox':x==='Teacher Performance & AI Insights'?'/modules/teacher-performance':'/modules/student-360'} className="glass-card-dark flex items-center justify-between p-4 text-sm font-bold hover:border-orange-400/40">{x}<ArrowRight size={16} className="text-orange-400"/></Link>)}</div></div><div className="grid gap-4 sm:grid-cols-2">{audiences.map(([title,desc,Icon])=><div key={title} className="rounded-3xl border border-white/10 bg-white/5 p-6"><Icon className="text-orange-400"/><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{desc}</p></div>)}</div></div></section>

      <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><div className="relative"><div className="absolute -inset-5 rounded-[3rem] bg-orange-100/70 blur-3xl"/><div className="relative grid grid-cols-2 gap-3"><img src="/images/screenshots/Student.png" alt="Student mobile experience" className="rounded-[2rem] border border-slate-200 shadow-xl"/><img src="/images/screenshots/Teacher.png" alt="Teacher mobile experience" className="mt-10 rounded-[2rem] border border-slate-200 shadow-xl"/></div></div><div><span className="brand-kicker">Your brand. Your apps.</span><h2 className="mt-4 text-3xl font-black text-slate-950 md:text-5xl">Institution-branded iOS & Android experiences.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Make the technology feel like part of your institution — not a generic third-party portal. EduBridge can power role-based mobile experiences under your institution’s name, logo and visual identity.</p><div className="mt-7 space-y-3">{['Student & parent experience','Teacher workflows','Driver and transport operations','Accounts, HR, examination, coordinator and HOD workflows'].map(x=><p key={x} className="flex gap-3 text-sm font-semibold text-slate-700"><CheckCircle2 size={19} className="shrink-0 text-orange-500"/>{x}</p>)}</div><Link href="/modules/branded-mobile-apps" className="mt-8 inline-flex items-center gap-2 font-bold text-orange-600">Explore branded mobile apps <ArrowRight size={18}/></Link></div></div></div></section>

      <section className="bg-orange-50 py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-5 lg:grid-cols-3"><div className="lg:col-span-1"><span className="brand-kicker">Schools + Colleges</span><h2 className="mt-4 text-3xl font-black text-slate-950">One platform, adaptable to your institution.</h2><p className="mt-4 leading-7 text-slate-600">Keep your existing institutional identity and workflows while moving to a connected digital platform.</p></div><Link href="/school-erp" className="group rounded-[2rem] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Building2 size={28} className="text-orange-500"/><h3 className="mt-8 text-2xl font-black text-slate-950">For Schools</h3><p className="mt-3 leading-7 text-slate-600">K-12 academics, fees, examinations, transport, parent engagement, student wellbeing and campus operations.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-orange-600">School ERP <ArrowRight size={17}/></span></Link><Link href="/college-erp" className="group rounded-[2rem] bg-slate-950 p-7 text-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><GraduationCap size={28} className="text-orange-400"/><h3 className="mt-8 text-2xl font-black">For Colleges</h3><p className="mt-3 leading-7 text-slate-300">A flexible campus management foundation for academic administration, students, staff, finance, communication and operations.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-orange-400">College ERP <ArrowRight size={17}/></span></Link></div></div></section>
      <FinalCTA/>
    </main><Footer/>
  </div>
}
