import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import FinalCTA from '../../components/FinalCTA';
import SEOHead from '../../components/SEOHead';
import RoleCatalog from '../../components/RoleCatalog';
import { roles } from '../../data/roleCatalog';

export default function RolesPage(){
  return <div className="bg-slate-50 text-slate-800"><SEOHead title="EduBridge ERP Role Workspaces | Principal, HOD, Examination & More" description="Explore role-specific EduBridge ERP workspaces for management, principals, HODs, examination teams, teachers, students, accounts, HR, transport and campus operations." path="/roles" keywords={['school ERP roles','HOD ERP','examination management ERP','principal dashboard','college ERP roles']}/><Navbar/><main><section className="relative overflow-hidden bg-slate-950 py-20 text-white md:py-28"><div className="hero-grid absolute inset-0 opacity-25"/><div className="hero-glow hero-glow-one"/><div className="relative mx-auto max-w-7xl px-5 text-center md:px-8"><span className="brand-kicker brand-kicker-dark">Role-Aware ERP</span><h1 className="mx-auto mt-5 max-w-5xl text-4xl font-black tracking-tight md:text-6xl">Every role gets a <span className="gradient-text">purpose-built workspace.</span></h1><p className="mx-auto mt-6 max-w-3xl text-base leading-7 text-slate-300 md:text-lg">From Principal and HOD to Examination, Accounts, HR, Transport, Driver, Teacher and Student — EduBridge keeps each team focused while connecting everyone to the same institution data.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><span className="pill-dark">{roles.length} role experiences</span><span className="pill-dark">Schools + Colleges</span><span className="pill-dark">Web + Mobile</span><span className="pill-dark">Permission Aware</span></div></div></section><section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-10"><span className="brand-kicker">Role Workspaces</span><h2 className="mt-3 text-3xl font-black text-slate-950 md:text-4xl">See exactly what each team can do</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Understand the workflows, responsibilities and connected capabilities available to each team across the institution.</p></div><RoleCatalog/></div></section><FinalCTA/></main><Footer/></div>;
}
